"""add case analyses table

Revision ID: 511d7083a781
Revises: 954b29d19d99
Create Date: 2026-02-10 17:32:50.076306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511d7083a781'
down_revision = '954b29d19d99'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_analyses_case_id'), 'case_analyses', ['case_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_analyses_case_id'), table_name='case_analyses')
    op.drop_table('case_analyses')
    # ### end Alembic commands ###
