"""add executive_data to case_analyses

Revision ID: 9a8399a95b9a
Revises: b68d6ace4546
Create Date: 2026-02-16 23:45:24.968000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8399a95b9a'
down_revision = 'b68d6ace4546'
branch_labels = None
depends_on = None

def upgrade() -> None:

    # 1️⃣ Adiciona tenant_id como nullable temporariamente

    op.add_column("audit_logs", sa.Column("tenant_id", sa.Integer(), nullable=True))



    # 2️⃣ Backfill seguro (DEV assume tenant_id=1)

    op.execute("UPDATE audit_logs SET tenant_id = 1 WHERE tenant_id IS NULL")



    # 3️⃣ Torna NOT NULL após garantir preenchimento

    op.alter_column("audit_logs", "tenant_id", nullable=False)



    # 4️⃣ Cria índice e FK

    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)

    op.create_foreign_key(None, "audit_logs", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE")



    # 5️⃣ Nova coluna executive_data

    op.add_column("case_analyses", sa.Column("executive_data", sa.JSON(), nullable=True))



    # 6️⃣ Ajustes estruturais

    op.alter_column("case_analyses", "summary", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)

    op.drop_index(op.f("uq_cases_tenant_case_number"), table_name="cases")

    op.create_unique_constraint("uq_cases_tenant_case_number", "cases", ["tenant_id", "case_number"])

    op.drop_column("users", "is_active")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_cases_tenant_case_number', 'cases', type_='unique')
    op.create_index(op.f('uq_cases_tenant_case_number'), 'cases', ['tenant_id', 'case_number'], unique=True)
    op.alter_column('case_analyses', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('case_analyses', 'executive_data')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'tenant_id')
    # ### end Alembic commands ###
